version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:management
    # restart: always
    networks:
      - tools
    privileged: true
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672
    volumes:
      - /Users/caoping/www/docker/docker-file/mq/rabbitmq/data:/var/lib/rabbitmq
      - /Users/caoping/www/docker/docker-file/mq/rabbitmq/logs:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
