services:

  rabbitmq:
    image: rabbitmq:3.13.7-management
    # restart: always
    networks:
      mq_net:
        ipv4_address: 172.25.0.2
    privileged: true
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672
    volumes:
      - /Users/caoping/www/docker/docker-file/mq/rabbitmq/data:/var/lib/rabbitmq
      - /Users/caoping/www/docker/docker-file/mq/rabbitmq/logs:/var/log/rabbitmq
      - /Users/caoping/www/docker/docker-file/mq/rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /Users/caoping/www/docker/docker-file/mq/rabbitmq/config/10-default-guest-user.conf:/etc/rabbitmq/conf.d/10-default-guest-user.conf
      - /Users/caoping/www/docker/docker-file/mq/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez:/opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8


  kafka01:
    image: bitnami/kafka:3.8.1
    container_name: kafka01
    # restart: always
    privileged: true
    user: root
    networks:
      mq_net:
        ipv4_address: 172.25.0.3
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      # 允许使用Kraft
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER
      # 定义kafka服务端socket监听端口（Docker内部的ip地址和端口）
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      #定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.7:9092
      # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
      - KAFKA_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka01:9093
      # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 设置broker最大内存，和初始内存
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
    volumes:
      - /Users/caoping/www/docker/docker-file/mq/kafka/broker:/bitnami/kafka:rw

  kafkaui:
    container_name: kafkaui
    image: provectuslabs/kafka-ui:latest
    # restart: always
    privileged: true
    networks:
      mq_net:
        ipv4_address: 172.25.0.4
    depends_on:
      - kafka01
    ports:
      - '8050:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka01
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka01:9092
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - SERVER_SERVLET_CONTEXT_PATH=/
      - AUTH_TYPE=LOGIN_FORM
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin123


networks:
  mq_net:
    driver: bridge
    name: mq_net
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1