version: '3.9'

services:

  zipkin-mysql:
    image: openzipkin/zipkin:latest
    container_name: zipkin-mysql
    ports:
      - '9410:9410'
      - '9411:9411'
    networks:
      - mysql_net
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_DB=zipkin_config
      - MYSQL_USER=root
      - MYSQL_PASS=123456
      - MYSQL_HOST=mysql
      - MYSQL_TCP_PORT=3306
  
  zipkin-es:
    image: openzipkin/zipkin:latest
    container_name: zipkin-es
    networks:
      - es_net
    ports:
      - '9410:9410'
      - '9411:9411'
    environment:
      - TZ=Asia/Shanghai
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=123456
      - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    
  skywalking-oap:
    image: apache/skywalking-oap-server:latest
    container_name: skywalking-oap
    privileged: true
    networks:
      - skywalking
      - es_net
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      TZ: Asia/Shanghai
    volumes:
      - ./skywalking/config/alarm-settings.yml:/skywalking/config/alarm-settings.yml
  
  skywalking-ui:
    image: apache/skywalking-ui:latest
    container_name: skywalking-ui
    privileged: true
    networks:
      - skywalking
    depends_on:
      - skywalking-oap
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
      TZ: Asia/Shanghai

networks:
  mysql_net:
    name: app_net
    external: true
  es_net:
    name: elkf8_es8_net
    external: true
  skywalking:
    driver: bridge
