version: '3.9'

services:

  zipkin-mysql:
    image: openzipkin/zipkin:latest
    container_name: zipkin-mysql
    ports:
      - '9410:9410'
      - '9411:9411'
    network_mode: host
    networks:
      - mysql_net
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_DB=zipkin_config
      - MYSQL_USER=root
      - MYSQL_PASS=123456
      - MYSQL_HOST=mysql
      - MYSQL_TCP_PORT=3306
  
  zipkin-es:
    image: openzipkin/zipkin:latest
    container_name: zipkin-es
    networks:
      - es_net
    ports:
      - '9410:9410'
      - '9411:9411'
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch:9200
    
networks:
  mysql_net:
    name: app_net
    external: true
  es_net:
    name: elkf_es_net
    external: true
