sources:
  friends_source:   
    type: "file"
    include:
      - /logs/ruoyi/logs/**/*.log

transforms:
  friends_transform:
    type: remap
    inputs:
      - friends_source
    source: |
      . = parse_regex!(.message, r'^(?P<logDay>\d+-\d+-\d+) (?P<logTime>\d+:\d+:\d+) \[thread:(?P<thread>.*)\] \[traceId:(?P<traceId>.*)\] \[ip:(?P<ip>.*)\] \[level:(?P<level>.*)\] \[className:(?P<className>.*)\] \[userId:(?P<userId>.*)\] \[username:(?P<username>.*)\] - (?P<content>.*$)')
      .timestamp = .logDay + " " + .logTime
      .appName = "friends-server"
      .level = replace(.level, " ", "")
      del(.logDay)
      del(.logTime)

  
sinks:
  # jiaoyou_print:
  #   type: "console"
  #   inputs: ["my_transform"]
  #   encoding:
  #     codec: "json"
  friends_vlogs:
    inputs:
      - friends_transform
    type: elasticsearch
    endpoints:
      - http://192.168.1.6:9428/insert/elasticsearch/
    mode: data_stream
    auth:
      strategy: "basic"
      user: "admin"
      password: "admin123"
    api_version: v8
    healthcheck:
      enabled: false
    query:
      _msg_field: content
      _time_field: timestamp
      _stream_fields: appName

# api:
#   enabled: true
#   address: "0.0.0.0:8686"