version: "3.8"
services:
  kafka1:
    container_name: kafka01
    image: 'bitnami/kafka'
    user: root
    networks:
      - kafka_net
    ports:
      - '19092:9092'
      - '19093:9093'
    environment:
      # 允许使用Kraft
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 定义kafka服务端socket监听端口（Docker内部的ip地址和端口）
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      #定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.31.128:19092
      # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
      - KAFKA_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=1
      - KAFKA_CFG_NODE_ID=1
       # 集群地址
      # - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka11:9093,2@kafka22:9093,3@kafka33:9093
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka01:9093
      # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 设置broker最大内存，和初始内存
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
    volumes:
      - /home/docker/kafka/broker:/bitnami/kafka:rw
    
  # https://blog.csdn.net/Vector97/article/details/128539970
  kafkaui:
    container_name: kafkaui
    image: provectuslabs/kafka-ui:latest
    networks:
      - kafka_net
    ports:
      - '8050:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka01
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka01:9092
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - SERVER_SERVLET_CONTEXT_PATH=/
      - AUTH_TYPE=LOGIN_FORM
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin123