version: '3.8'

services:

  nginx:
    image: nginx:latest
    # restart: always
    privileged: true
    container_name: nginx
    ports:
      - 5173:5173
      - 8443:443
    volumes:
      - /Users/caoping/www/docker/docker-file/base/nginx/html:/etc/nginx/html
      - /Users/caoping/www/docker/docker-file/base/nginx/www:/var/www
      - /Users/caoping/www/docker/docker-file/base/nginx/nginx.conf/:/etc/nginx/nginx.conf
      - /Users/caoping/www/docker/docker-file/base/nginx/cert:/etc/nginx/cert
      - /Users/caoping/www/docker/docker-file/base/nginx/conf.d:/etc/nginx/conf.d
      - /Users/caoping/www/docker/docker-file/base/nginx/logs:/var/log/nginx
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai


  tools:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: tools
    privileged: true
    # restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8001:80 


  mysql8:
    image: mysql:latest
    # restart: always
    networks:
      - tools
    privileged: true
    container_name: mysql
    ports:
      - 8306:3306
    volumes:
      - /Users/caoping/www/docker/docker-file/base/mysql8/data:/var/lib/mysql
      - /Users/caoping/www/docker/docker-file/base/mysql8/conf:/etc/mysql/conf.d
      - /Users/caoping/www/docker/docker-file/base/mysql8/my.cnf:/etc/mysql/my.cnf
      - /Users/caoping/www/docker/docker-file/base/mysql8/logs:/var/log/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456


  mysql57:
    image: mysql:5.7.30
    # restart: always
    networks:
      - tools
      - external_net
    privileged: true
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - /Users/caoping/www/docker/docker-file/base/mysql57/data:/var/lib/mysql
      - /Users/caoping/www/docker/docker-file/base/mysql57/conf:/etc/mysql/conf.d
      - /Users/caoping/www/docker/docker-file/base/mysql57/my.cnf:/etc/mysql/my.cnf
      - /Users/caoping/www/docker/docker-file/base/mysql57/logs:/var/log/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456


  redis:
    image: redis:latest
    # restart: always
    networks:
      - tools
      - external_net
    privileged: true
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /Users/caoping/www/docker/docker-file/base/redis/data:/data
      - /Users/caoping/www/docker/docker-file/base/redis/redis.conf:/etc/redis/redis.conf

    command: redis-server /etc/redis/redis.conf


  jenkins:
    image: jenkins/jenkins:2.440.2
    #restart: always
    networks:
      - tools
    privileged: true
    container_name: jenkins
    ports:
      - 8000:8080
      - 50000:50000
    volumes:
      - /etc/localtime:/etc/localtime
      # chown -R 1000 
      - /Users/caoping/www/docker/docker-file/base/jenkins:/var/jenkins_home
      # 传入maven包jdk包
      - /Users/caoping/bin/apache-maven-3.6.3:/usr/local/maven
      - /Users/caoping/bin/jdk1.8.0_381:/usr/local/java
      - /usr/bin/git:/usr/local/git
      # 在容器中使用宿主机的docker
      - /usr/bin/docker:/usr/bin/docker
      # 注意要在jenkins容器中开放权限
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - TZ=Asia/Shanghai

    # command: /bin/bash -c "mkdir /dockerData; chown -R 1000 /dockerData"


  registry:
    image: registry
    # restart: always
    networks:
      - tools
    privileged: true
    container_name: registry
    ports:
      - 5000:5000
    environment:
      - REGISTRY_AUTH=htpasswd
      #相对于数据卷auth的路径，不要写宿主机全路径
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - /home/docker-data/registry/config.yml:/etc/docker/registry/config.yml
      - /home/docker-data/registry/auth:/auth
      - /home/docker-data/registry/data:/var/lib/registry


  rabbitmq:
    image: rabbitmq:management
    # restart: always
    networks:
      - tools
    privileged: true
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672
    volumes:
      - /Users/caoping/www/docker/docker-file/base/rabbitmq/data:/var/lib/rabbitmq
      - /Users/caoping/www/docker/docker-file/base/rabbitmq/logs:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  mongo:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - /home/mydata/mongo/data:/data/db
    restart: always
    ports:
      - 27017:27017
      

networks:
  es_net:
    driver: bridge
  tools:
    driver: bridge
  external_net:
    name: app_net
    external: true
