version: '3.8'
services:
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - kafka_net
    # restart: true
    ports:
      - "2181:2181"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - /Users/caoping/www/docker/docker-file/kafka/zookeeper/data:/data
      - /Users/caoping/www/docker/docker-file/kafka/zookeeper/datalog:/datalog
      - /Users/caoping/www/docker/docker-file/kafka/zookeeper/conf:/conf
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka01
    networks:
      - kafka_net
    # restart: true
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zk
    environment:
      # KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.4
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.4:9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - "/etc/localtime:/etc/localtime"
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/caoping/www/docker/docker-file/kafka/kafka/logs:/kafka/logs

  kafkaui:
    image: freakchicken/kafka-ui-lite
    container_name: kafkaui
    networks:
      - kafka_net
    # restart: true
    depends_on:
      - kafka
    ports:
      - "8889:8889"
    
networks:
  kafka_net:
    driver: bridge